server:
  port: 8086

spring:
  datasource:
    ssm:
      driver-class-name: com.mysql.jdbc.Driver
      password: root
      url: jdbc:mysql://localhost:3306/websocket_chatroom?serverTimezone=GMT%2B8
      username: root

logging:
  config: classpath:log4j2.xml

